#!/bin/bash

#
# Copyright (c)      2021 Triad National Security, LLC
#                         All rights reserved.
#
# This file is part of the bueno project. See the LICENSE file at the
# top-level directory of this distribution for more information.
#

set -e

test_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

pushd "$test_dir" || exit 1

./test.bueno
./test.bueno.run

popd || exit 1

# vim: ts=4 sts=4 sw=4 expandtab
