#!/bin/bash

#
# Copyright (c)      2021 Triad National Security, LLC
#                         All rights reserved.
#
# This file is part of the bueno project. See the LICENSE file at the
# top-level directory of this distribution for more information.
#

# Straightforward tests for the bueno command.

# shellcheck source=./common.sh
source common.sh

test_start

bueno run --help

bueno run -a none -o output -p ./run-scripts/hello.py
bueno run -a none -o output -p ./run-scripts/shell-cmds.py
bueno run -a none -o output -p ./run-scripts/ooo.py
bueno run -a none -o output -p ./run-scripts/runcmds.py
bueno run -a none -o output -p ./run-scripts/datasink.py
bueno run -a none -o output -p ./run-scripts/format_path.py
bueno run -a none -o output -p ./run-scripts/parse_influxdb_line_proto.py

# Test suppression of data files.
bueno run -a none -o /dev/null -p ./run-scripts/dataflush.py


test_end

# vim: ts=4 sts=4 sw=4 expandtab
