# Example Dockerfile that builds an image containing a simple MPI program.

FROM debian:stretch

RUN \
apt-get update \
&& \
apt-get install -y --no-install-recommends \
openssh-client \
libmpich-dev \
gcc \
make \
&& \
rm -rf /var/lib/apt/lists/*

COPY nbody .

WORKDIR /nbody
RUN make CC=mpicc
