#!/bin/bash
#
# Copyright (c)      2020 Triad National Security, LLC
#                         All rights reserved.
#
# This file is part of the bueno project. See the LICENSE file at the
# top-level directory of this distribution for more information.
#

bueno run -a none --extras .:./mypackage -p ./extras.py
