# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: QA

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install --upgrade codecov coverage==4.5.4
        python -m pip install --upgrade flake8
        python -m pip install --upgrade mypy==0.910
        python -m pip install --upgrade pylint
        python -m pip install --upgrade bandit
        # Package dependencies
        python -m pip install --upgrade pyyaml
        python -m pip install types-PyYAML
    - name: Packaging
      run: |
        qa/run-packaging-tests
    - name: Style Checks
      run: |
        qa/run-flake8-tests
    - name: Type Checks
    # For interactive debugging
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    # For interactive debugging
      run: |
        qa/run-mypy-tests
    - name: Code Analysis
      run: |
        qa/run-pylint-tests
    - name: Security
      run: |
        qa/run-bandit-tests
    - name: Regression
      run: |
        qa/run-bueno-tests
