#!/bin/bash
#
# Copyright (c)      2021 Triad National Security, LLC
#                         All rights reserved.
#
# This file is part of the bueno project. See the LICENSE file at the
# top-level directory of this distribution for more information.
#

echo "Running bueno test suite"

test_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

pushd "$test_dir" || exit 1

../tests/run-test-suite

popd || exit 1
