#!/bin/bash

#
# Copyright (c) 2020-2022 Triad National Security, LLC
#                         All rights reserved.
#
# This file is part of the bueno project. See the LICENSE file at the
# top-level directory of this distribution for more information.
#

set -e

echo "Running QA suite........................................................."

# Always first to install 3rd-party dependencies.
./qa/run-packaging-tests
./qa/run-flake8-tests
./qa/run-mypy-tests
./qa/run-pylint-tests
./qa/run-bandit-tests
./qa/run-bueno-tests

echo "QA suite completed successfully.................................."

# vim: ts=4 sts=4 sw=4 expandtab
