#!/bin/bash
#
# Copyright (c) 2020-2021 Triad National Security, LLC
#                         All rights reserved.
#
# This file is part of the bueno project. See the LICENSE file at the
# top-level directory of this distribution for more information.
#

echo "Reporting on Security Standing"

# pip install bandit

bandit --version

bandit ./bueno -r
